name: notify-bungeecord
version: 1.0-SNAPSHOT
author: rlqu
main: app.simplecloud.plugin.notify.bungeecord.BungeeCordNotifyPlugin
website: 'https://github.com/simplecloudapp/notify-plugin'
depends: [simplecloud-api]